#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#include <stddef.h>
#include <stdint.h>

#ifdef BARE_METAL

#ifdef XPAR_DDR_MEM_BASEADDR
#define PLATFORM_DDR_BASE ((uintptr_t)XPAR_DDR_MEM_BASEADDR)
#else
#define PLATFORM_DDR_BASE 0x80000000u
#endif

#ifndef WEIGHTS_DDR_BASE
#define WEIGHTS_DDR_BASE  (PLATFORM_DDR_BASE + 0x08000000u)
#endif
#ifndef WEIGHTS_DDR_SIZE
#define WEIGHTS_DDR_SIZE  (16u * 1024u * 1024u)
#endif
#ifndef WEIGHTS_W8_DDR_BASE
#define WEIGHTS_W8_DDR_BASE  WEIGHTS_DDR_BASE
#endif
#ifndef WEIGHTS_W8_DDR_SIZE
#define WEIGHTS_W8_DDR_SIZE  (8u * 1024u * 1024u)
#endif

#ifndef DETECT_HEAD_BASE
#define DETECT_HEAD_BASE  (PLATFORM_DDR_BASE + 0x0E000000u)
#endif
#ifndef DETECT_HEAD_SIZE
#define DETECT_HEAD_SIZE  (9u * 1024u * 1024u)
#endif

#ifndef IMAGE_AND_FEATURE_BASE
#define IMAGE_AND_FEATURE_BASE (PLATFORM_DDR_BASE + 0x0F000000u)
#endif
#ifndef IMAGE_AND_FEATURE_SIZE
#define IMAGE_AND_FEATURE_SIZE (16u * 1024u * 1024u)
#endif

#ifndef IMAGE_DDR_BASE
#define IMAGE_DDR_BASE    IMAGE_AND_FEATURE_BASE
#endif
#define IMAGE_HEADER_SIZE 24u
#define IMAGE_DATA_SIZE   (3u * 640u * 640u * sizeof(float))
#define IMAGE_DDR_SIZE    (IMAGE_HEADER_SIZE + IMAGE_DATA_SIZE)
#define IMAGE_A16_DATA_SIZE  (3u * 640u * 640u * sizeof(int16_t))
#define IMAGE_A16_DDR_SIZE   (IMAGE_HEADER_SIZE + IMAGE_A16_DATA_SIZE)

#ifndef FEATURE_POOL_BASE
#define FEATURE_POOL_BASE (PLATFORM_DDR_BASE + 0x02000000u)
#endif
#ifndef FEATURE_POOL_SIZE
#if defined(USE_W8A16)
#define FEATURE_POOL_SIZE (48u * 1024u * 1024u)
#else
#define FEATURE_POOL_SIZE (32u * 1024u * 1024u)
#endif
#endif

#ifndef DETECTIONS_OUT_BASE
#define DETECTIONS_OUT_BASE (IMAGE_AND_FEATURE_BASE + IMAGE_AND_FEATURE_SIZE - 4096u)
#endif

#ifndef CPU_MHZ
#define CPU_MHZ 100
#endif

#endif /* BARE_METAL */

#endif /* PLATFORM_CONFIG_H */
